### ISSUE TITLE
`to24Hour()` argument "meridian" spelled incorrectly

### ISSUE THREAD

**Issue by dkreft** [jimf/hour-convert#1]
The argument to `to24Hour()` is incorrectly spelled as "meridian." The correct spelling is actually "meridiem."

http://www.todayifoundout.com/index.php/2010/06/what-am-and-pm-stand-for/
https://www.timeanddate.com/time/am-and-pm.html

I have a pull request that I can submit which will add support for `meridiem` and be 100% backwards compatible with `meridian`. :-)

**Comment by jimf** [comment]
Hah, well TIL! I've probably been spelling this wrong for a good 10 years. Sounds good. A PR would be welcome!

**Comment by dkreft** [comment]
Cool. I'll need you to grant me permissions to submit a PR, then. :-)

**Comment by jimf** [comment]
You should be able to fork the repo and make a pull request from there: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

If you want, feel free to post a diff here and I'll work it in. Otherwise I can just address it myself, but won't be able to get to it until sometime tonight.

**Comment by dkreft** [comment]
Ah, I see. I'm used to github at work were we submit PRs from feature
branches. :-)

-dan

**Comment by dkreft** [comment]
Submitted #2

**Comment by jimf** [comment]
Fixed with #2.
